server:
  port: 8018 #${PORT:0}
  #error:    
    #include-message: always

management:
  endpoints:
    web:
      exposure:
        include: "*"
  endpoint:
    health:
      show-details: always

#EUREKA CUSTOMER
eureka:
  instance:
    prefer-ip-address: true
    #instance-id: ${spring.application.name}:${random.value}
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka

#DB MONGO
spring:
  data:
    mongodb:
      host: localhost
      port: 27017
      database: dbtransactionsaving