server:  
  port: 8059 #${PORT:0}
  #error:    
    #include-message: always

#ACTUATOR
management:
  endpoints:
    web:
      exposure:
        include: "*"
  endpoint:
    health:
      show-details: always

#EUREKA CUSTOMER
eureka:
  instance:
    prefer-ip-address: true
    #instance-id: ${spring.application.name}:${random.value}
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka

#KAFKA    
#REDIS
#DB MONGO
spring:
  cloud:
    stream:
      bindings:
        input:
          destination: money-transaction
  redis:
    host: localhost
    port: 6379   
  data:
    mongodb:
      host: localhost
      port: 27017
      database: yankiAccount